### ISSUE TITLE
A few setup documentation ?

### ISSUE THREAD

**Issue by aneveux** [zachtaylor/JPokemon#19]
Hi @zachtaylor !

I'm following your project for a few weeks/months right now, and it looks really interesting to me. I already had a look at the source code, but I'm not sure about how to execute everything properly. Could it be possible for you to provide a small documentation about how to setup a test environment with your project ? I mean, just the steps to achieve to launch the game locally, if it's possible regarding the current implementation.

Thanks a lot for your help ;)

**Comment by zachtaylor** [comment]
Hi @aneveux !

Thank you so much for your interest! As of right now ("Bellsprout"), it is not possible to launch the game :P. I closed out Bellsprout because all of the work that needed to be done to make executable would have been removed for "Cubone." Right now, the code is basically a core. If you poke around the wiki, you can see the plan for iteration 3, which includes battle creation, removal, world exploration, etc. 

I have been meaning to write some developer docs for some time. Is that what you're looking for? I can also write some docs on environment setup while in Cubone.

Thanks for your comment, and thank you again for your interest! 

Zach

**Comment by aneveux** [comment]
Hi @zachtaylor ! 

Yeah actually I was searching for some developer documentation, in fact I read all your wiki pages, but I was searching for a quick way to setup an environment, and mainly a test environment on top of your project. In fact, as I'm really interested in your project, I was searching for a way to get a development environment on my workstation, to be able to test the source code the way you do, and perhaps to have some information about the features you'd like to implement to see if I can help :)

I saw on the wiki some information about what you'd like to include in the iterations, so with a few documentation, perhaps I could help ;)

Thanks a lot for your answers !

**Comment by zachtaylor** [comment]
Developer docs are on the way! After (hopefully) tonight the code should be executable. This documentation may come today or tomorrow.

I would really appreciate contributions. If you fork and then pull request, I can get a taste for your coding style. I am willing to add you as a contributor if you'd like, moving forward.

Zach

**Comment by aneveux** [comment]
Hi @zachtaylor !

Thanks a lot for such a quick answer :) I'll stay tuned and have a look at your documentation as soon as it'll be available.

Regarding contributions, I'll use this pullrequest mechanism, I'm quite familiar to it, and I think that's the best way to do, at least in a first time :) I think I won't be really active in the next few days because I'll leave for some vacations, but I'm really interested in contributing some features :)

Again, thanks a lot ;)

**Comment by zachtaylor** [comment]
You can see some setup documentation up on the wiki now!
