### ISSUE TITLE
Add build.xml for building by Ant.

### ISSUE THREAD

**Issue by o01eg** [zachtaylor/JPokemon#3]
Is it possible to add Ant support for bulding project without installing eclipse?

**Comment by zachtaylor** [comment]
I'd like it but I don't know much about Ant. I'll add an issue and you can push those changes if you want. I don't know how to use ant but if other people do, and it would be easier, they can.

**Comment by shortstuffsushi** [comment]
Ant is actually entirely separate from Eclipse, so it should easily be possible. Is there any reason you would want to use it? Do you not develop in Eclipse?

**Comment by o01eg** [comment]
I want to don't install Eclipse only for compiling. As I know Ant files can be generated by Eclipse.

**Comment by shortstuffsushi** [comment]
If that's how you're hoping to do it, you should download Ant from [Apache](http://ant.apache.org/). Once you've downloaded it, read some of the documentation, and try writing a build.xml for the project.

Since it's a pretty simple project, you should only have one target, which would likely be (off the top of my head) a javac, or jar call for the src directory, or something along those lines that would compile the src files into a single JPokemon.jar.

You'll also need to include the manifest, but I'm pretty sure Zach has already specified a manifest file in the project. If you're able to accomplish this, commit the build.xml to the project and we'll include it for anyone else who desires to compile this way.

**Comment by zachtaylor** [comment]
I was working with Ant today at work, trying to figure it out. Matt wanted that project's source and a build.xml, but he was in a meeting when i needed help with the build.xml... So i get ant a little better now.

I have nothing against including a build.xml, and i do have a manifest already. I agree with sushi, if you pull request on a build.xml, one of us will pull it

**Comment by zachtaylor** [comment]
as per using it, I don't think I would, but it wouldn't hurt.

**Comment by mhorner** [comment]
I could probably help out with making an ant script happen... still necessary?

**Comment by mhorner** [comment]
Just submitted the pull request (#23) that will build the jar file.  Should be available as soon as Zach does what he needs to.

**Comment by zachtaylor** [comment]
Thanks @mhorner
